<a href="https://colab.research.google.com/github/kylegilde/kata-code-wars/blob/main/Pandas_and_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculating Running Total

Description

Given a posts table that contains a created_at timestamp column write a query that returns date (without time component), a number of posts for a given date and a running (cumulative) total number of posts up until a given date. The resulting set should be ordered chronologically by date.

Desired Output

The resulting set should look similar to the following:

```
date       | count | total
-----------+-------+-------
2017-01-26 |    20 |    20
2017-01-27 |    17 |    37
2017-01-28 |     7 |    44
2017-01-29 |     8 |    52
```

date - (DATE) date

count - (INT) number of posts for a date

total - (INT) a running (cumulative) number of posts up until a date

In [9]:
s = \
"""
id	created_at	title
1	2023-08-14 07:28:36 +0000	Ut soluta fuga est.
2	2023-08-14 14:20:16 +0000	Tempora eum quas similique.
3	2023-08-14 11:53:15 +0000	Ea optio non eum.
4	2023-08-14 04:15:49 +0000	Quia ad sint est.
5	2023-08-13 12:46:10 +0000	Accusantium corporis eius quos.
6	2023-08-13 21:38:24 +0000	Dolorem labore voluptatem nisi.
7	2023-08-13 11:24:03 +0000	Et et vero et.
8	2023-08-13 06:12:18 +0000	Aut sed facilis odit.
9	2023-08-13 14:05:04 +0000	Eum et iste odio.
10	2023-08-13 10:13:38 +0000	Quam repellat omnis corporis.
11	2023-08-13 06:41:38 +0000	Labore quibusdam asperiores iure.
12	2023-08-13 04:52:09 +0000	Impedit reprehenderit dolor eligendi.
13	2023-08-13 18:21:37 +0000	Eos a eveniet mollitia.
14	2023-08-13 07:57:27 +0000	Harum et soluta deleniti.
15	2023-08-13 17:10:28 +0000	Ipsa consequatur molestias expedita.
16	2023-08-13 18:43:37 +0000	Laudantium officia quod voluptas.
17	2023-08-13 07:10:59 +0000	Consequatur ipsum quasi laboriosam.
18	2023-08-13 18:28:34 +0000	Provident eum nemo unde.
19	2023-08-13 22:25:33 +0000	Laborum enim dolor neque.
20	2023-08-13 17:23:09 +0000	Perspiciatis reprehenderit non est.
21	2023-08-13 03:41:53 +0000	Consequuntur eveniet quae iste.
22	2023-08-13 17:43:46 +0000	Et itaque eligendi facilis.
23	2023-08-13 04:59:27 +0000	Atque quidem dolores maxime.
24	2023-08-13 02:21:01 +0000	Sint reprehenderit ut aspernatur.
25	2023-08-12 12:50:29 +0000	Consectetur praesentium architecto qui.
26	2023-08-12 05:08:33 +0000	Incidunt fugiat laborum et.
27	2023-08-12 03:44:26 +0000	Et ullam ut ut.
28	2023-08-12 11:15:44 +0000	Omnis ut eum et.
29	2023-08-12 05:47:11 +0000	Ut illum repellat distinctio.
30	2023-08-12 09:22:56 +0000	In eum rerum rerum.
31	2023-08-11 07:45:33 +0000	Similique doloribus voluptatem ut.
32	2023-08-11 01:14:24 +0000	Possimus aut aut provident.
33	2023-08-10 13:57:11 +0000	Nobis quia consequatur eligendi.
34	2023-08-10 09:19:43 +0000	Voluptas dolores impedit quos.
35	2023-08-10 21:22:54 +0000	Commodi aliquid velit nobis.
36	2023-08-10 10:57:13 +0000	Aspernatur unde nihil tenetur.
37	2023-08-10 12:56:24 +0000	Non esse voluptatibus eaque.
38	2023-08-10 00:59:18 +0000	Illum sunt nam alias.
39	2023-08-10 11:11:12 +0000	Rerum eos nihil dolorem.
40	2023-08-10 18:36:59 +0000	Suscipit consequuntur voluptatem saepe.
41	2023-08-10 15:43:31 +0000	Quia iure et perspiciatis.
42	2023-08-10 20:44:29 +0000	Sunt beatae dolor consequuntur.
43	2023-08-10 07:33:10 +0000	Consequatur corporis velit ratione.
44	2023-08-10 04:28:46 +0000	Sint aut animi nam.
45	2023-08-09 06:04:17 +0000	Laboriosam corrupti vel facilis.
46	2023-08-09 10:44:30 +0000	Perspiciatis tempore blanditiis ut.
47	2023-08-09 16:41:33 +0000	Eaque consequatur quia magni.
48	2023-08-09 05:00:46 +0000	Molestiae sunt repellendus qui.
49	2023-08-09 23:41:33 +0000	Enim id ab optio.
50	2023-08-09 18:08:37 +0000	Et consequatur sequi eaque.
51	2023-08-09 22:03:11 +0000	Harum est voluptatem fugit.
52	2023-08-09 04:33:08 +0000	Pariatur iste enim sunt.
53	2023-08-09 17:16:07 +0000	Dignissimos sint sunt ab.
54	2023-08-09 00:18:05 +0000	Dolor error repudiandae in.
55	2023-08-09 03:19:36 +0000	Quo quo id autem.
56	2023-08-09 17:28:32 +0000	Quo aut et facilis.
57	2023-08-08 15:22:28 +0000	Minus quidem et mollitia.
58	2023-08-08 19:25:09 +0000	Itaque inventore corrupti optio.
59	2023-08-08 17:24:42 +0000	Aut quaerat qui pariatur.
60	2023-08-08 10:13:59 +0000	Corrupti magni nihil quia.
61	2023-08-08 17:35:50 +0000	Quisquam aut et delectus.
62	2023-08-08 04:07:44 +0000	Explicabo omnis nostrum et.
63	2023-08-08 23:43:16 +0000	Expedita nemo et qui.
64	2023-08-08 17:47:59 +0000	Ipsam alias a vel.
65	2023-08-08 05:33:35 +0000	Officia consequuntur maiores est.
66	2023-08-08 08:41:51 +0000	Veritatis eligendi tempore mollitia.
67	2023-08-08 15:31:20 +0000	Autem nihil ut rem.
68	2023-08-08 16:18:24 +0000	Quia minus enim id.
69	2023-08-08 05:23:35 +0000	Minima perferendis deleniti aperiam.
70	2023-08-08 03:41:14 +0000	Dolorem non nobis in.
71	2023-08-08 01:42:32 +0000	Consectetur sequi cupiditate cum.
72	2023-08-07 10:31:14 +0000	Atque autem molestias odio.
73	2023-08-07 13:04:03 +0000	Doloremque voluptate aspernatur quo.
74	2023-08-07 12:41:56 +0000	Ad atque porro quia.
75	2023-08-07 23:29:24 +0000	Pariatur culpa voluptatem et.
76	2023-08-07 18:35:14 +0000	Eos rerum consequatur rerum.
77	2023-08-07 00:54:04 +0000	Odit pariatur unde aut.
78	2023-08-07 01:42:58 +0000	Ipsam autem consequatur nulla.
79	2023-08-07 18:45:29 +0000	Ipsum iste ad placeat.
80	2023-08-07 09:53:24 +0000	Expedita ut consectetur dolores.
81	2023-08-07 11:10:07 +0000	Deleniti hic maxime illo.
82	2023-08-07 01:53:30 +0000	Ipsam fuga omnis sed.
83	2023-08-07 18:42:26 +0000	Laboriosam voluptas quasi mollitia.
84	2023-08-07 10:36:30 +0000	Nihil iusto quia id.
85	2023-08-07 15:33:36 +0000	Quibusdam deleniti odit rerum.
86	2023-08-07 18:33:45 +0000	Aperiam asperiores accusantium nostrum.
87	2023-08-07 22:00:27 +0000	Ab quis commodi qui.
88	2023-08-07 18:25:33 +0000	Nostrum quia aperiam vel.
89	2023-08-07 15:52:00 +0000	Autem quia impedit odio.
90	2023-08-07 11:00:16 +0000	Nulla perferendis delectus et.
91	2023-08-06 21:27:46 +0000	Odit nam magni nisi.
92	2023-08-06 08:10:53 +0000	Molestias quos sed ut.
93	2023-08-06 09:57:13 +0000	Ab debitis consequatur id.
94	2023-08-06 20:18:29 +0000	Exercitationem perspiciatis et corporis.
95	2023-08-06 22:15:57 +0000	Ex dicta eligendi suscipit.
96	2023-08-06 02:13:51 +0000	Atque accusantium eum vitae.
97	2023-08-06 10:12:41 +0000	Ducimus sed et voluptatem.
98	2023-08-06 19:14:13 +0000	Sint omnis non itaque.
99	2023-08-06 23:47:38 +0000	Sed voluptas quo eligendi.
"""

In [20]:
from io import StringIO
import pandas as pd
df = pd.read_csv(StringIO(s), sep="\t")
df.info()
(
    df
    .assign(date=lambda df: df.created_at.astype("datetime64").dt.date)
    .groupby("date")
    .size()
    .rename("n")
    .reset_index()
    .assign(total=lambda df: df.n.cumsum())
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          99 non-null     int64
 1   created_at  99 non-null     object
 2   title       99 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.4+ KB

         date   n  total
0  2023-08-06   9      9
1  2023-08-07  19     28
2  2023-08-08  15     43
3  2023-08-09  12     55
4  2023-08-10  12     67
5  2023-08-11   2     69
6  2023-08-12   6     75
7  2023-08-13  20     95
8  2023-08-14   4     99

```
SELECT
    date,
    count,
    CAST(SUM(count) OVER(ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS INTEGER) AS total
FROM (
    SELECT
      CAST(created_at AS DATE) AS date,
      COUNT(*) AS count
    FROM
      posts
    GROUP BY 1
) AS p
```